# This file sets up the Configuration for many of the GitHub Actions and Automations used in this repository 
# Based off the config.yml file used at TTW: https://github.com/the-turing-way/the-turing-way

#################### COMMUNITY BUILDING #####################
# To welcome new community members and support interactions
# with GitHub, we've set up a WelcomeBot using the templates 
# provided at https://github.com/behaviorbot/welcome.

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  :tada: Thanks for opening your first issue in the AIM RSF Synthetic Data repository! :tada:
# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  :sparkling_heart: Thanks for opening this pull request! :sparkling_heart: Make sure you have described what changes you've made and are suggesting, and then request someone to review the PR.    
# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first Pull Request! :tada:
  
# This Welcome is based on The Turing Way and the [behaviourbot's welcome](https://github.com/behaviorbot/welcome?installation_id=26730891&setup_action=install). Material from The Turing Way has been used and adapted under a CC-BY license. Attributions go to [The Turing Way Community. (2021). The Turing Way: A handbook for reproducible, ethical and collaborative research (1.0.1)](https://doi.org/10.5281/zenodo.6533831) Images from the Banners were created by Scriberia for The Turing Way community and are used under a CC-BY licence.
